### PR TITLE
net: Enable IP_FREEBIND on listeners

### LINKED ISSUE #238: systemd: add dependency on network-online.target
I've encountered following bug from time to time:
```
zrepl version=v0.2.0-11-gdc39c81 GOOS=linux GOARCH=amd64 Compiler=gc
host zrepl[1488]: starting daemon
host zrepl[1488]: [pull_source]: starting job
host zrepl[1488]: [_prometheus]: starting job
host zrepl[1488]: [connection_loss_tidyup]: starting job
host zrepl[1488]: [connection_loss_tidyup]: wait for wakeups
host zrepl[1488]: [_control]: starting job
host zrepl[1488]: [_prometheus]: cannot listen err="listen tcp 10.0.0.200:9091: bind: cannot assign requested add
host zrepl[1488]: [_prometheus]: job exited
host zrepl[1488]: panic: runtime error: invalid memory address or nil pointer dereference
host zrepl[1488]:         panic: runtime error: invalid memory address or nil pointer dereference
host zrepl[1488]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x81ea4d]
host zrepl[1488]: goroutine 25 [running]:
host zrepl[1488]: net/http.(*onceCloseListener).close(...)
host zrepl[1488]:         /usr/local/go/src/net/http/server.go:3330
host zrepl[1488]: sync.(*Once).doSlow(0xc00018b060, 0xc0000c7bc0)
host zrepl[1488]:         /usr/local/go/src/sync/once.go:66 +0xe3
host zrepl[1488]: sync.(*Once).Do(...)
host zrepl[1488]:         /usr/local/go/src/sync/once.go:57
host zrepl[1488]: net/http.(*onceCloseListener).Close(0xc00018b050, 0xc0003a6000, 0xe0)
host zrepl[1488]:         /usr/local/go/src/net/http/server.go:3326 +0x77
host zrepl[1488]: panic(0xb1d1c0, 0x11d7d90)
host zrepl[1488]:         /usr/local/go/src/runtime/panic.go:679 +0x1b2
host zrepl[1488]: net/http.(*onceCloseListener).Accept(0xc00018b050, 0xc000120020, 0xb0fd20, 0x11d7ce0, 0xbee6e0)
host zrepl[1488]:         <autogenerated>:1 +0x32
host zrepl[1488]: net/http.(*Server).Serve(0xc0003a6000, 0x0, 0x0, 0x0, 0x0)
host zrepl[1488]:         /usr/local/go/src/net/http/server.go:2896 +0x286
host zrepl[1488]: net/http.Serve(...)
host zrepl[1488]:         /usr/local/go/src/net/http/server.go:2468
host zrepl[1488]: github.com/zrepl/zrepl/daemon.(*prometheusJob).Run(0xc000109940, 0xd19ec0, 0xc00018a930)
host zrepl[1488]:         /go/src/github.com/zrepl/zrepl/daemon/prometheus.go:75 +0x23e
host zrepl[1488]: github.com/zrepl/zrepl/daemon.(*jobs).start.func1(0xc0000f68c0, 0xd22c40, 0xc000116ee0, 0xd1ba4
host zrepl[1488]:         /go/src/github.com/zrepl/zrepl/daemon/daemon.go:220 +0x121
host zrepl[1488]: created by github.com/zrepl/zrepl/daemon.(*jobs).start
host zrepl[1488]:         /go/src/github.com/zrepl/zrepl/daemon/daemon.go:216 +0x52e
host systemd[1]: zrepl.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
host systemd[1]: zrepl.service: Failed with result 'exit-code'.
```

My workaround for this was adding network-online dependency to the systemd-file:
/lib/systemd/system/zrepl.service
```
[Unit]
...
Wants=network-online.target
After=network-online.target
```

Maybe there should be added an `Restart=on-failure` too

### PR DESCRIPTION
**Pull request by juergenhoetzel**
Allows to bind to an address even if it is not actually (yet or ever)
configured. Fixes #238

Rationale:
https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/#whatdoesthismeanformeadeveloper

### CODE REVIEW

**Comment by juergenhoetzel** [comment]
Build failure on FreeBSD:

 
Seems FreeBSD uses a different option
```
     If	the IP_BINDANY option is enabled on a SOCK_STREAM, SOCK_DGRAM or a
     SOCK_RAW socket, one can bind(2) to any address, even one not bound to
     any available network interface in	the system.  This functionality	(in
     conjunction with special firewall rules) can be used for implementing a
     transparent proxy.	 The PRIV_NETINET_BINDANY privilege is needed to set
     this option.
```

File: util/freebind/freebind_stub.go [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+
+import (
+	"net"
+)
+
+// Dummy implementation: Like net.Listen (IP_FREEBIND isn't available
+// on non-linux platforms)
+func Listen(network, address string) (net.Listener, error) {
+	return net.Listen(network, address)
+}
```
Comment (juergenhoetzel) [inline util/freebind/freebind_stub.go]: Added dummy implementation for non-linux platforms which dont benefit (suffer :rofl: ) from  parallel  unit startup.

**Comment by problame** [comment]
Thanks for this PR!
I pushed my changes onto your branch:

- rename package to `tcpsock` (I find this more appropriate)
- config file wiring (defaults to false)
- freebsd impl (ipv6 support)

**Comment by problame** [comment]
Would you please test my changes for your setup, for both IPv4 and IPv6?
Please report back and feel free to push fixes on top of my changes!

**Comment by problame** [comment]
TODO:
- [ ] docs: update transports.rst and monitoring.rst
- [ ] docs: update changelog

**Comment by juergenhoetzel** [comment]
> Would you please test my changes for your setup, for both IPv4 and IPv6?
> Please report back and feel free to push fixes on top of my changes!

IPV4 (what i use) works.

Binding to a global scope IPV6 address also works.

But I can't bind to a link-local IPV6 address (not related to this issue):
```
Jan 02 19:51:24 pidsley zrepl[1249]: 2020-01-02T19:51:24+01:00 [ERRO][_prometheus]: cannot listen err="listen tcp [fe80::34fe:baff:fe83:6111]:9091: bind: invalid argument"
```

**Comment by problame** [comment]
For link-local addresses, you need to specify the interface name, i.e. `[fe80::34fe:baff:fe83:6111%eth0]:9091`

Could you please update the documentation + changelog (see TODO above)? (just push to this PR)

**Comment by juergenhoetzel** [comment]
> Could you please update the documentation + changelog (see TODO above)? (just push to this PR)

Done

**Comment by problame** [comment]
Thanks for your contribution. The change will be in 0.3, along with #259 !
